version: "3.7"

networks:
  wolf.network:
    driver: bridge

services:
  php:
    build: ./php
    restart: unless-stopped
    container_name: wolf.php
    tty: true
    depends_on:
      - mysql
      - redis
    networks:
      - wolf.network
    volumes:
      - ../:/var/www

  nginx:
    build: ./nginx
    container_name: wolf.nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "433:433"
      - "80:80"
    networks:
      - wolf.network
    volumes:
      - ../:/var/www

  #  mariadb:
  #    image: mariadb
  #    restart: unless-stopped
  #    container_name: wolf.mariadb
  #    tty: true
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - wolf.network
  #    volumes:
  #      - './mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './mysql/dbdata:/var/lib/mysql'
  #    environment:
  #      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
  #      MYSQL_USER: ${MYSQL_USER:-mysql}

  mysql:
    image: mysql:5
    restart: unless-stopped
    container_name: wolf.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - wolf.network
    volumes:
      - "./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_USER: ${MYSQL_USER:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: wolf.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - wolf.network
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: wolf.redis
    tty: true
    ports:
      - "6379:6379"
    networks:
      - wolf.network
    volumes:
      - ./redis:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD:-no}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
